hibernate.connection.url=jdbc:mysql://localhost:3306/t_person
hibernate.connection.username=root
hibernate.connection.password=LelVjhjp159

hibernate.connection.driver_class=com.mysql.cj.jdbc.Driver
hibernate.show_sql=true